services:
  web:
    image: ghcr.io/xiangyu-labs/mp3-tools:latest
    container_name: mp3-tools-web
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - NODE_ENV=production
      - TZ=Asia/Shanghai
